project:
  type: book
  output-dir: _book

book:
  title: "Pomorstvenost i opterećenja"
  author: "Josip Bašić"
  date: "2024-01-19"
  chapters:
    - index.qmd
    - part: "Teorija"
      chapters:
        - osnovni-pojmovi.qmd
        - opterecenja-na-konstrukciju.qmd
        - morski-valovi.qmd
        - matematicki-opis-valova.qmd
        - spektralni-opis.qmd
        - odziv-broda.qmd
        - operativnost.qmd
    - part: "Vježbe"
      chapters:
        - vjezba-hidrostatika-pontona.qmd
        - vjezba-ljuljanje-broda.qmd
        - vjezba-slamming-green-water.qmd
        - vjezba-val-na-ponton.qmd
        - vjezba-kontejnerski-brod.qmd
        - vjezba-razdioba-slucajne-varijable.qmd
        - vjezba-putanja-cestica.qmd
        - vjezba-spustanje-tendera.qmd
        - vjezba-pad-brzine.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: true

execute:
  enabled: true
  freeze: auto
