project:
  type: book
  output-dir: _book

book:
  title: "Pomorstvenost i opterećenja"
  author: "Josip Bašić"
  date: "2024-01-19"
  chapters:
    - index.qmd
    - part: "Teorija"
      chapters:
        - osnovni-pojmovi.md
        - opterecenja-na-konstrukciju.md
        - morski-valovi.md
        - matematicki-opis-valova.qmd
        - spektralni-opis.qmd
        - odziv-broda.qmd
        - operativnost.md
    - part: "Vježbe"
      chapters:
        - vjezba-hidrostatika-pontona.md
        - vjezba-ljuljanje-broda.md
        - vjezba-slamming-green-water.md
        - vjezba-val-na-ponton.md
        - vjezba-kontejnerski-brod.md
        - vjezba-razdioba-slucajne-varijable.md
        - vjezba-putanja-cestica.md
        - vjezba-spustanje-tendera.md
        - vjezba-pad-brzine.md

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: true

execute:
  enabled: true
  freeze: auto
